name: Tests

on:
  push:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.lock'
  pull_request:
    branches-ignore:
      - 'wip-*'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.lock'

jobs:
  test:
    name: build docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        exclude:
          # Python 3.10 only supports Sphinx 7.4.7
          - python-version: "3.10"
            sphinx-version: "8.2.3"
          - python-version: "3.10"
            sphinx-version: "9.0.4"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        sphinx-version:
          - "7.4.7"
          - "8.2.3"
          - "9.0.4"

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 22

    - run: npm ci
      working-directory: static

    - run: npm run build
      working-directory: static

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps
      run: python -m pip install -r requirements-dev.lock

    - name: Install Sphinx ${{ matrix.sphinx-version }}
      run: python -m pip install Sphinx==${{ matrix.sphinx-version }}

    - name: Build docs
      run: sphinx-build docs build/_html -b dirhtml
